### ISSUE TITLE
Role: Alert Manager

### ISSUE THREAD

**Issue by cpolizzi** [ddreggors/ocp-ansible-roles#1]
Consider support for Pager Duty and VictorOps.

**Comment by dadreggors** [comment]
Added a notice about other services being available to confiure and a link to prometheus alertmanager configuration at the top. I also added direct links to both Pager Duty and VictorOps configurations sections in the configuration doc in the tip at the bottom.

The idea of these roles is to give examples only. I want to leave some room for adaptation ;-)

**Comment by ddreggors** [comment]
Added a notice about other services being available to configure and a link to prometheus's alertmanager configuration at the top. I also added direct links to both Pager Duty and VictorOps configurations sections of the configuration doc in the tip at the bottom.

The idea of these roles is to give examples only. I want to leave some room for adaptation ;-)
